---
apiVersion: v1
kind: App
name: "AWS Fargate"
keywords: 
    - aws
    - serverless
    - containers
shortDescription: AWS serverless containers
description: |
  # AWS Fargate
  Amazon Web Services
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Amazon_Web_Services_Logo.svg/500px-Amazon_Web_Services_Logo.svg.png
website: https://aws.amazon.com/fargate/